### ISSUE TITLE
Todo 2101UG

### ISSUE THREAD

**Issue by yunpeng1234** [AY2122S1-CS2103T-F12-2/tp#290]
- [x] Unlink if you encounter and problems, please ..... section from TOC
- [x] Remove all : from features cos it looks weird in TOC
- [x] Unlink saving the data, editing the datafile from the TOC
- [x] Relink specification of fields to not be a subsection
- [x] Add picture for Components of UI + a short description
- [x] Add picture of the java dl webpage download with where to click
- [x] Add picture of downloading internwatcher with keep instead of discard
- [x] Add picture of mac putting Internwatcher in a clean folder
- [x] Add picture of window putting Internwatcher in a clean folder + 2x2 table to show the picture
- [x] Add picture for filter for jane in this command `filter g/4.80 c/Computer Science`
- [x] fix the last line of quick start + link to FAQ
- [x] e.g. missing an extra fullstop in view 2 T
- [x] filter picture needs to change
- [x] Find picture is wrong and need to be changed to find john + john doe
- [x] undo picture is wrong
- [x] Saving the data + Editing date file is to be deleted
- [x] Contact us link is not working for me
- [x] Add `<br>` to one of the FAQ
- [x] Maybe add a little pre amble to the specification of fields
- [x] Maybe hyperlink for email.
